apiVersion: v1
kind: Pod
metadata:
  name: vk-sp
spec:
  containers:
  - name: vk-sp
    image: stackpath.com/virtual-kubelet:0.0.1
    command: 
      - virtual-kubelet
    envFrom:
      - secretRef:
          name: sp-vk-secrets
      - configMapRef:
          name: sp-vk-location
    env:
      - name: VKUBELET_POD_IP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
  serviceAccountName: virtual-kubelet-sp
